#!/bin/bash
clear
#-----------@CYBERSSH-----------#
source ShellBot.sh
touch lista
[[ -z $1 ]] && {
    clear && echo "INFORME O TOKEN" && return 0
}
[[ ! -e RESET ]] && touch RESET
api_bot=$1
ShellBot.init --token "$api_bot" --monitor --flush
ShellBot.username

# - Funcao menu
menu() {
    local msg
        msg="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n"
        msg+="Olá <b>${message_from_first_name[$id]}</b>, BEM VINDO AO BOT CYBERSSH\n\n"
        msg+="Gere seu teste em nosso servidores 🇧🇷"
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
        --text "$(echo -e $msg)" \
        --reply_markup "$keyboard1" \
        --parse_mode html
        return 0
}

# - Funcao menu Compra
menu_compra() {
    [[ ${message_chat_id[$id]} == "" ]] && {
        id_chatuser="${callback_query_message_chat_id[$id]}"
    } || {
        id_chatuser="${message_chat_id[$id]}"
    }
    fun_menucompra $id_chatuser
    local msg
        msg="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n"
        msg+=" 1 LOGIN 15 R$  2 LOGIN 25 R$ 3 LOGIN 36R$."
        ShellBot.editMessageText --chat_id $id_chatuser \
        --message_id ${callback_query_message_message_id[$id]} \
        --text "$(echo -e $msg)" \
        --reply_markup "$keyboard2" \
        --parse_mode html
        (
          sleep 15
          local msg2
          msg2+="<b>BEM VINDO(a) AO MENU INICIAL</b>\n\n"
          ShellBot.editMessageText --chat_id "${id_chatuser}" --message_id "${callback_query_message_message_id[$id]}" \
          --text "$(echo -e $msg2)" \
          --reply_markup "$keyboard1" \
          --parse_mode html
          return 0
        ) &
        return 0
}

# - funcao criar ssh
criarteste() {
    [[ $(grep -wc ${callback_query_from_id} lista) != '0' ]] && {
      ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
        --text "Volte amanhã"
      return 0
    }
    usuario=$(echo Cyber$(( RANDOM% + 350 )))
    senha=$((RANDOM% + 9999))
    limite='1'
    tempo='6'
    tuserdate=$(date '+%C%y/%m/%d' -d " +2 days")
    useradd -M -N -s /bin/false $usuario -e $tuserdate > /dev/null 2>&1
    (echo "$senha";echo "$senha") | passwd $usuario > /dev/null 2>&1
    echo "$senha" > /etc/SSHPlus/senha/$usuario
    echo "$usuario $limite" >> /root/usuarios.db
    echo "#!/bin/bash
pkill -f "$usuario"
userdel --force $usuario
grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
rm /etc/SSHPlus/senha/$usuario > /dev/null 2>&1
rm -rf /etc/SSHPlus/userteste/$usuario.sh" > /etc/SSHPlus/userteste/$usuario.sh
    chmod +x /etc/SSHPlus/userteste/$usuario.sh
    at -f /etc/SSHPlus/userteste/$usuario.sh now + $tempo hour > /dev/null 2>&1
    echo ${callback_query_from_id} >> lista
    # - ENVIA O SSH
    ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
    --text "$(echo -e "✅ <b>Teste Criado com sucesso!</b> ✅\n\nUSUARIO: <code>$usuario</code>\nSENHA: <code>$senha</code>\n\n⏳ Expira em: $tempo Hora")" \
    --parse_mode html
    return 0
}
    
#enviar sks
enviarsks() {
    ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
        --text " 🌐 AGUARDE..."
    ShellBot.sendDocument --chat_id ${callback_query_message_chat_id} \
        --document "@/root/base.apk" \
    return 0
    

    }

#informacoes usuario
infouser () {
	ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
	--text "$(echo -e "Nome:  ${message_from_first_name[$(ShellBot.ListUpdates)]}\nUser: @${message_from_username[$(ShellBot.ListUpdates)]:-null}")\nID: ${message_from_id[$(ShellBot.ListUpdates)]} " \
	--parse_mode html
	return 0
}

unset botao1
botao1=''
ShellBot.InlineKeyboardButton --button 'botao1' --line 1 --text '🇧🇷 CRIAR TESTE 🇧🇷' --callback_data 'gerarssh'
ShellBot.InlineKeyboardButton --button 'botao1' --line 2 --text '🇧🇷 COMPRAR LOGIN 🇧🇷' --callback_data 'menucompra'
ShellBot.InlineKeyboardButton --button 'botao1' --line 3 --text '🇧🇷 BAIXAR APP 🇧🇷' --callback_data 'sksenviar'
ShellBot.regHandleFunction --function criarteste --callback_data gerarssh
ShellBot.regHandleFunction --function menu_compra --callback_data menucompra
ShellBot.regHandleFunction --function enviarsks --callback_data sksenviar
unset keyboard1
keyboard1="$(ShellBot.InlineKeyboardMarkup -b 'botao1')"
unset botao2
botao2=''
ShellBot.InlineKeyboardButton --button 'botao2' --line 1 --text '🌐 COMPRE AQUI 🌐'  --callback_data '3' --url 't.me/LOCKED_SSH' # pv
unset keyboard2
keyboard2="$(ShellBot.InlineKeyboardMarkup -b 'botao2')"
while :; do
   [[ "$(date +%d)" != "$(cat RESET)" ]] && {
   	echo $(date +%d) > RESET
   	echo ' ' > lista
   }
  ShellBot.getUpdates --limit 100 --offset $(ShellBot.OffsetNext) --timeout 24
  for id in $(ShellBot.ListUpdates); do
    (
      ShellBot.watchHandle --callback_data ${callback_query_data[$id]}
      comando=(${message_text[$id]})
      [[ "${comando[0]}" = "/menu"  || "${comando[0]}" = "/start" ]] && menu
      [[ "${comando[0]}" = "/comprar" || "${comando[0]}" = "/teste" ]] && menu
    ) &
  done
done
